audio:
  Ali:
    access_key_id: ${ALI_ACCESS_KEY_ID}
    access_key_secret: ${ALI_ACCESS_KEY_SECRET}
    app_key: ${ALI_APP_KEY}
  Azure:
    service_region: ${AZURE_SERVICE_REGION}
    speech_key: ${AZURE_SPEECH_KEY}
  Tencent:
    access_key_id: ${TENCENT_ACCESS_KEY_ID}
    access_key_secret: ${TENCENT_ACCESS_KEY_SECRET}
    app_key: ${TENCENT_APP_KEY}
  local_recognition:
    fasterwhisper:
      compute_type: int8
      device_type: cuda
      model_name: medium
    provider: fasterwhisper
  local_tts:
    GPTSoVITS:
      server_location: http://127.0.0.1:9880/
    chatTTS:
      server_location: http://127.0.0.1:8080/
    provider: chatTTS
  provider: Tencent
captioning:
  provider: Azure
llm:
  Azure:
    api_key: ${AZURE_OPENAI_API_KEY}
    base_url: http://base.url.openai
    model_name: null
  Baichuan:
    api_key: ${BAICHUAN_API_KEY}
    model_name: Baichuan3-Turbo
  DeepSeek:
    api_key: ${DEEPSEEK_API_KEY}
    base_url: https://api.deepseek.com/
    model_name: deepseek-chat
  Moonshot:
    api_key: ${MOONSHOT_API_KEY}
    model_name: moonshot-v1-8k
  Ollama:
    api_key: YOUR_API_KEY
    base_url: http://127.0.0.1:11434/
    model_name: llama3
  OpenAI:
    api_key: ${OPENAI_API_KEY}
    model_name: gpt-3.5-turbo
  Qianfan:
    api_key: ${QIANFAN_API_KEY}
    model_name: ERNIE-Bot-turbo
    secret_key: ${QIANFAN_SECRET_KEY}
  Tongyi:
    api_key: ${TONGYI_API_KEY}
    model_name: qwen-turbo
  provider: DeepSeek
aigc:
  provider: DeepSeek
  api_key: ${DEEPSEEK_API_KEY}
  DeepSeek:
    model_name: deepseek-chat
    base_url: https://api.deepseek.com/
  OpenAI:
    model_name: gpt-3.5-turbo
    base_url: https://api.openai.com/v1/
  Moonshot:
    model_name: moonshot-v1-8k
    base_url: https://api.moonshot.cn/v1/
  Azure:
    model_name: gpt-3.5-turbo
    base_url: https://your-resource.openai.azure.com/
  Qianfan:
    model_name: ERNIE-Bot-turbo
    api_key: ${QIANFAN_API_KEY}
    secret_key: ${QIANFAN_SECRET_KEY}
  Baichuan:
    model_name: Baichuan3-Turbo
    api_key: ${BAICHUAN_API_KEY}
  Tongyi:
    model_name: qwen-turbo
    api_key: ${TONGYI_API_KEY}
publisher:
  auto_publish: true
  common:
    collection: 集合名称
    enable: true
    tags: []
    title_prefix: 标题前缀
  content_location: null
  douyin:
    collection: 集合名称
    enable: true
    title_prefix: 标题前缀
  driver_location: null
  driver_type: chrome
  kuaishou:
    collection: 集合名称
    domain:
      enable: true
      level1: 教育
      level2: 语言教育
    enable: true
    title_prefix: 标题前缀
  shipinhao:
    collection: 集合名称
    enable: true
    original: false
    title_prefix: 标题前缀
  xiaohongshu:
    collection: 集合名称
    enable: true
    title_prefix: 标题前缀
resource:
  pexels:
    api_key: API_KEY
  pixabay:
    api_key: API_KEY
  provider: pexels
test_mode: false
ui:
  language: zh-CN
video: null
