audio_language: zh-CN
audio_output_file: D:\MoneyPrinterPlus\MoneyPrinterPlus-windows\work\1757488831582.wav
audio_output_file_list: []
audio_speed: normal
audio_type: remote
background_music: null
background_music_dir: "P:\\\u56E2\u961F\u7A7A\u95F4\\\u5357\u4EAC\u9AD8\u6052\u6587\
  \u5316\u4F20\u5A92\u6709\u9650\u516C\u53F8\\\u77E9\u9635\u89C6\u9891\u6BCF\u65E5\
  \u4E0A\u4F20\\B \u87F9\u5BB4\\20250916\\bgm"
background_music_volume: 0.3
batch_completed: true
batch_folder_path: D:\MoneyPrinterPlus\MoneyPrinterPlus-windows\final\batch_20250916_110845
batch_in_progress: false
batch_start_index: 0
batch_total_videos: 2
batch_video_counter: 2
captioning_lines: 2
captioning_output: D:\MoneyPrinterPlus\MoneyPrinterPlus-windows\work\1757488831802.srt
enable_background_music: true
enable_subtitles: true
enable_video_overlay: true
enable_video_transition_effect: true
is_mix_video: true
overlay_image_path: C:\Users\plove\Downloads\20250915-162140.png
overlay_mode: single
overlay_opacity: 1.0
random_background_music: true
recognition_audio_type: remote
result_video_file: D:\MoneyPrinterPlus\MoneyPrinterPlus-windows\final\batch_20250916_110845\2.mp4
scene_number: 0
skip_tts: false
subtitle_border_color: '#000000'
subtitle_border_width: 1
subtitle_color: '#FFFFFF'
subtitle_font: ARIALN
subtitle_font_size: 12
subtitle_margin_v: 66
subtitle_position: 2
tts_text_file: "P:\\\u56E2\u961F\u7A7A\u95F4\\\u5357\u4EAC\u9AD8\u6052\u6587\u5316\
  \u4F20\u5A92\u6709\u9650\u516C\u53F8\\\u77E9\u9635\u89C6\u9891\u6BCF\u65E5\u4E0A\
  \u4F20\\A \u7A46\u65AF\u6797\\20250915\\tts"
use_tts_text_for_subtitles: false
video_dir_list:
- "P:\\\u56E2\u961F\u7A7A\u95F4\\\u5357\u4EAC\u9AD8\u6052\u6587\u5316\u4F20\u5A92\u6709\
  \u9650\u516C\u53F8\\\u77E9\u9635\u89C6\u9891\u6BCF\u65E5\u4E0A\u4F20\\B \u87F9\u5BB4\
  \\20250916\\materials"
video_fps: 30
video_layout: portrait
video_scene_folder_1: "P:\\\u56E2\u961F\u7A7A\u95F4\\\u5357\u4EAC\u9AD8\u6052\u6587\
  \u5316\u4F20\u5A92\u6709\u9650\u516C\u53F8\\\u77E9\u9635\u89C6\u9891\u6BCF\u65E5\
  \u4E0A\u4F20\\A \u7A46\u65AF\u6797\\20250915\\materials"
video_scene_text_1: D:\MoneyPrinterPlus\aigc\publish\20250905\tts
video_segment_max_length: 10
video_segment_min_length: 5
video_size: 1080x1920
video_transition_effect_duration: '1'
video_transition_effect_type: xfade
video_transition_effect_value: fade
videos_count: 5
